### PR TITLE
17 add support for different can data bytes lengths

### PR DESCRIPTION
**Pull request by HusseinAbdelhamid**

### CODE REVIEW

**Review by marius-meissner — CHANGES_REQUESTED** [review]
Previously, the generic parameter was fixed by the library and bound to the message type. We were therefore able to use this as a validation for the payload length.
But since the parameter now comes from the caller of the library, the validation has become useless, hasn't it? If the parameter is not used anywhere else, I have not found any use, then we could remove L completely, couldn't we?

**Comment by HusseinAbdelhamid** [comment]
> Previously, the generic parameter was fixed by the library and bound to the message type. We were therefore able to use this as a validation for the payload length.

Exactly but that means L becomes fixed to 8 for any CAN2.0 message, and if the caller tries to create a message with only 4 data bytes then ```.copy_from_slice()``` call will fail because ```buff``` and ```data``` have to be the same length
https://github.com/atlas-aero/rt-mcp2517/blob/f476e586bb83acf53acbd730d6ccc50526846eef/src/can.rs#L351-L353


> But since the parameter now comes from the caller of the library, the validation has become useless, hasn't it? If the parameter is not used anywhere else, I have not found any use, then we could remove L completely, couldn't we?

It is still validated I think, in the ```setup_header``` fn. L is just used here to create this local data buffer which is passed on to the ```transfer``` fn since we can't directly pass the ```message.buff```, Do you have any suggestion on how to optimize that?

**Comment by marius-meissner** [comment]
Alright, thanks for the explanation.
I just missed the reference code. Then it's fine.

**Review by marius-meissner — APPROVED** [review]
LGTM

**Pull request merged**
